### ISSUE TITLE
Cannot add images

### ISSUE THREAD

**Issue by iambenmitchell** [nachonavarro/Pages#12]
Hello, I am trying to make a TikTok style UI.

I have tried this:

```
struct ContentView: View {
     @State var index: Int = 0
   var body: some View {
            Pages(currentPage: $index, navigationOrientation: .vertical) {
                Image("ModelX")
            }
        }
    }
```

However I get this error:` Cannot convert value of type 'Image' to closure result type '[AnyView]'`

I have also tried doing this:

```
struct ContentView: View {
     @State var index: Int = 0
   var body: some View {
            Pages(currentPage: $index, navigationOrientation: .vertical) {
                NewsView()
            }
        }
    }

struct NewsView: View{
    var body: some View {
        Image("modelX")
    }
    
}
```

However I get the same error but lightly different: `Cannot convert value of type 'NewsView' to closure result type '[AnyView]'`

Anyhelp is appreciated, I am not a noob but I am new to swiftUI

**Comment by iambenmitchell** [comment]
Solved: I am an idiot, I got this error before I added a second item. 

You must have at least two items ie

```
Image("")
Image("")
```

I got thrown off because I usually stop as soon as I see an error

**Comment by nachonavarro** [comment]
No worries :)

As you can read in the docs, the Pages view needs more than one page. Otherwise the compiler treats what's inside Pages as a [closure](https://stackoverflow.com/questions/58409839/function-builder-not-working-when-only-one-value).

**Comment by iambenmitchell** [comment]
> No worries :)
> 
> As you can read in the docs, the Pages view needs more than one page. Otherwise the compiler treats what's inside Pages as a [closure](https://stackoverflow.com/questions/58409839/function-builder-not-working-when-only-one-value).

I am having another issue now where images don’t behave correctly: https://twitter.com/a_mrbenmitchell/status/1251582028606246914?s=21

**Comment by iambenmitchell** [comment]
#13
