### ISSUE TITLE
Image clipping/buggy

### ISSUE THREAD

**Issue by iambenmitchell** [nachonavarro/Pages#13]
Hello, I am trying to make a UI like TikTok but the images are behaving weirdly. It works fine on my 11 pro max but not on a screen size smaller, it sort of jumps around. [Screenshot](https://imgur.com/a/e4ysQWw)

<blockquote class="imgur-embed-pub" lang="en" data-id="a/e4ysQWw"  ><a href="//imgur.com/a/e4ysQWw">Pages image issue (clipping)</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by iambenmitchell** [comment]
Decided to open it up here since it is a separate issue

**Comment by nachonavarro** [comment]
Could you send a short reproducible example so I can test it on my end?
