### ISSUE TITLE
Background colors should be clear.

### ISSUE THREAD

**Issue by agiokas** [nachonavarro/Pages#2]
Hi, background colors of the ViewController's.view should be .clear.

PageViewController.swift:52
Pages.swift:105
ModelPages:115

I somehow cannot create a brach....

**Comment by nachonavarro** [comment]
I'm not following, what are you trying to achieve? Could you paste your code?

**Comment by agiokas** [comment]
The viewController's views have a default color of white, so you cannot see what it beneath the PageViewController.

**Comment by nachonavarro** [comment]
Did you manage to check the changes? They should be up in the latest version.
