### ISSUE TITLE
Parent.controllers is different than current.controllers.

### ISSUE THREAD

**Issue by neHCuoHEpa** [nachonavarro/Pages#3]
I have follow situation.
`struct HomeView {
...
Pages(currentPage: self.$currentPage)
{
   ChannelsView()
   PublicationsView()
   MarkedView()
}
...
`
The problem is coming from that in PublicationsView, Im realoading some data and view should be rendered again. Then "controllers" array is updated and refill with newest views.
But in the Coordinator the parent reference keep the first "controllers" array. That follow to a bug:
in "viewControllerBefore" and "viewControllerAfter" -> "parent.controllers.firstIndex(of: viewController)" is returning nil and the pages cannot be changed.
I cannot find a easy solution. Could you help me?

**Comment by neHCuoHEpa** [comment]
I found a solution. Just need to update parent value of coordinator before any changes. Like this
`func updateUIViewController(_ pageViewController: UIPageViewController,
                                context: Context)
    {
        context.coordinator.parent = self
        pageViewController.setViewControllers(
            [controllers[currentPage]], direction: .forward, animated: false
        )
    }`

**Comment by jpmcglone-airside** [comment]
For those reading along, update your `updateUIViewController` in `PageViewController` to:

```swift
func updateUIViewController(_ pageViewController: UIPageViewController, context: Context) {
    context.coordinator.parent = self
    pageViewController.setViewControllers(
        [controllers[currentPage]], direction: .forward, animated: false
    )
}
```

Worked for me!

**Comment by nachonavarro** [comment]
Awesome, thanks guys. I don't have time right now but I'll try to add it this weekend. If anybody wants to submit a pull request feel free :)

**Comment by nachonavarro** [comment]
Fixed
