### ISSUE TITLE
Changing the view hierarchy makes scrolling stop working

### ISSUE THREAD

**Issue by danielsaidi** [nachonavarro/Pages#9]
Thanks for a great library!

I am facing a problem where scrolling stops working when the view hierarchy changes. At first, everything works great. However, if I modify the view hierarchy in any way (e.g. by setting a state property that causes a label to change), the page view's scroll just starts bouncing back. The problem appears in both `Pages` and `ModelPages`.

Do you have any idea what may be causing this?

**UPDATE** The problem exists in `0.1.3`, but is solved in `master`. Can you consider making a `0.1.4` version of master?

**Comment by nachonavarro** [comment]
Ah yes, of course. I'm on it.

**Comment by danielsaidi** [comment]
Perfect, thank you! I'm using it both for onboarding tutorials and a multi-page keyboard extension. It works great :)

**Comment by LualdiD** [comment]
Hi, this issue is back in the latest version
